# Generated by Django 3.1 on 2020-08-28 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200828_0741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='photo',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
