# Generated by Django 3.1 on 2020-08-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200828_0945'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductImage',
            new_name='Image',
        ),
    ]
