# Generated by Django 3.1 on 2020-08-30 08:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20200828_0952'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(default='photo', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(default='photo', upload_to='product'),
        ),
        migrations.AlterField(
            model_name='image',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='products.product'),
        ),
    ]
